### PR TITLE
fixed: bin/lfeexec is not been triggered when compiling...

### PR DESCRIPTION
**Pull request by diasbruno**
so, we need compile by hand and then call make.

### CODE REVIEW

**Comment by diasbruno** [comment]
Hi @vic, I'm trying to figure it out why when running the tests, asdf is forcing the test to checkout back on master. 
Any ideas on why this is happening?

**Comment by vic** [comment]
@diasbruno Yep, the test are running with code from master since you have to specify the branch it needs to checkout `asdf plugin test --asdf-plugin-gitref YOUR_BRANCH ...`.  

Actually, we should better update this repo to use the `plugin-test` action from https://github.com/asdf-vm/actions instead of using travis. The action will make sure the code for the PR is the one being used during test.

All you have to do is include a workflow.yml. (the following example is from https://github.com/asdf-community/asdf-direnv/blob/master/.github/workflows/workflow.yml)

```yaml
  plugin_test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: direnv version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by vic** [comment]
Can you test using the following command: 

```
 asdf plugin-test lfe https://github.com/vic/asdf-lfe --asdf-tool-version latest --asdf-plugin-gitref master lfe --version
```

just replace `master` with the PR commit it should be testing, I guess there's a travis env-var having that value, I just can't remember it's name right now.

**Comment by diasbruno** [comment]
Thanks, @vic! I'll give it a try.

**Comment by diasbruno** [comment]
Great. It's compiling now. 

`asdf plugin-test lfe https://github.com/vic/asdf-lfe --asdf-tool-version latest --asdf-plugin-gitref ${TRAVIS_COMMIT} echo "ok"`

The only thing is that we can't run `lfe --version' since this command is not available.

**Comment by vic** [comment]
Replace `echo ok` with some command from `lfe` that is evidence of it being properly installed, it could be anything valid on an LFE installation, like `lfe --help`

**Comment by diasbruno** [comment]
Done.

**Comment by diasbruno** [comment]
Do you want to move to github actions? I can help setting it up.

**Comment by vic** [comment]
Nice work, @diasbruno. Thank you!

**Comment by diasbruno** [comment]
Thanks for the help, @vic. Glad to help.

**Pull request merged**
